services:
  db:
    image: mysql:8.0
    ports:
      - "4406:3306"
    volumes:
      - db_data:/var/lib/mysql
    env_file: .env.db
  api:
    image: binhntdev/api:latest 
    build: ./api
    depends_on:
      - db
    ports:
      - "3000:3000"
    env_file: .env.api
volumes:
  db_data:
