-- Add down migration script here
ALTER TABLE Nutabi.DataSource
    MODIFY CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MODIFY LastUpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE Nutabi.Location
    MODIFY CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

