-- Add up migration script here
ALTER TABLE Nutabi.Location
    MODIFY CreatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE Nutabi.DataSource
    MODIFY CreatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    MODIFY LastUpdatedAt TIMESTAMP NOT NULL
        DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;